# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'horário', 'verbose_name_plural': 'horários'},
        ),
        migrations.AlterField(
            model_name='horario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(choices=[('Seg', 'Segunda-feira'), ('Ter', 'Terça-feira'), ('Quar', 'Quarta-feira'), ('Qui', 'Quinta-feira'), ('Sex', 'Sexta-feira'), ('Sáb', 'Sábado'), ('Sex', 'Domingo')], max_length=4, verbose_name='Dia da semana'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='local',
            field=models.TextField(verbose_name='Endereço'),
        ),
    ]
