# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160225_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Preço')),
                ('dias', models.CharField(choices=[('1x por semana', '1x por semana'), ('2x por semana', '2x por semana'), ('3x por semana', '3x por semana'), ('4x por semana', '4x por semana'), ('5x por semana', '5x por semana'), ('6x por semana', '6x por semana'), ('7x por semana', '7x por semana')], max_length=13, verbose_name='Dias por semana')),
                ('atividade', models.CharField(max_length=50, verbose_name='Atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
    ]
