# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=20, verbose_name='Sobrenome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('foto', models.ImageField(default='img/no-img-professor.jpg', upload_to='img/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name_plural': 'Professor',
                'verbose_name': 'Professor',
            },
        ),
        migrations.AlterField(
            model_name='preco',
            name='dias',
            field=models.CharField(choices=[('1x por semana', '1x por semana'), ('2x por semana', '2x por semana'), ('3x por semana', '3x por semana'), ('4x por semana', '4x por semana'), ('5x por semana', '5x por semana'), ('6x por semana', '6x por semana'), ('7x por semana', '7x por semana'), ('Aula livre', 'Aula livre')], max_length=13, verbose_name='Dias por semana'),
        ),
    ]
