# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160315_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(default='nairalirayoga/core/static/img/no-img-professor.jpg', upload_to='nairalirayoga/core/static/img/', verbose_name='Foto'),
        ),
    ]
