# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import nairalirayoga.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160316_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(default='img/no-img-professor.jpg', height_field=models.IntegerField(default=0), upload_to=nairalirayoga.core.models.upload_location, verbose_name='Foto', width_field=models.IntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='professor',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
