# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import nairalirayoga.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160316_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=models.ImageField(default='no-img-professor.jpg', height_field='height_field', upload_to=nairalirayoga.core.models.upload_location, verbose_name='Foto', width_field='width_field'),
        ),
    ]
