# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160316_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preco',
            name='atividade',
            field=models.CharField(choices=[('Aula de Yoga', 'Aula de Yoga')], max_length=50, verbose_name='Atividade'),
        ),
    ]
