# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import nairalirayoga.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20160316_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, default='no-img-professor.png', height_field='height_field', null=True, upload_to=nairalirayoga.core.models.upload_location, verbose_name='Foto', width_field='width_field')),
                ('carrosel', models.BooleanField(verbose_name='No Carrosel')),
                ('height_field', models.IntegerField(default=0, verbose_name='Largura')),
                ('width_field', models.IntegerField(default=0, verbose_name='Altura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name_plural': 'Imagens',
                'verbose_name': 'Imagem',
            },
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
    ]
