# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160921_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
    ]
