# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:42
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160921_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=django_markdown.models.MarkdownField(verbose_name='Conteúdo'),
        ),
    ]
