# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160921_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
    ]
